import * as React from "react";
import "./termsOfUseStyles.css";
export default () => {
    return (
        <div >
            <div className="text-styling">
         <p className="termsOfuse-redColor-heading">Terms of Use</p>
         <div className="scroll-bar background-color-popup">
         <p className="terms-of-use-subheading">Introduction</p>
         <p className="terms-of-use-para">The website www.bitlabs.in and mobile apps (collectively referred to as the “Platform”) and the information, services and other materials contained therein are provided and operated by Tekworks Private Limited (referred to as “we”, “us” or “bitLabs”). bitLabs offers curated and specially designed industry-relevant certification programs online (“Programs”).</p>
         <p className="terms-of-use-para">Please review our Terms of Use, Privacy Policy and other policies available on the Platform (collectively referred to as the “Terms”) that govern the use of the Platform and Programs. Each Program may have a separate set of terms dealing with refunds, deferrals, payments, etc. governing such Programs, and our corporate clients may have executed separate written agreements with us, which, in the event of a conflict, will supersede these Terms to the extent of the conflicting provisions.</p>
         <p className="terms-of-use-para">These Terms shall apply to bitLabs hosted mobile apps, WhatsApp groups, Facebook groups, Instagram pages, Facebook pages, email/SMS/phone communications and other social media forums hosted by bitLabs, which shall be deemed to be part of the ‘Platform’ by reference. You acknowledge that certain parts of the Platform, as mentioned above, are provided by third-party service providers, and you agree to abide by their terms and conditions. bitLabs shall not be responsible for any disruption of services caused by such third-party service providers.</p>
         <p className="terms-of-use-para">Please note that the use of the Platform and Programs constitutes an unconditional agreement to follow and be bound by the Terms. Although you may "bookmark" a particular portion of the Platform and thereby bypass these Terms, your use of the Platform still binds you to these Terms.</p>
         <p className="terms-of-use-para">We may change these Terms from time to time without prior notice. You should review this page regularly. Your continued use of the Platform and Programs after changes have been made will be taken to indicate that you have read and accepted those changes. You should not use the Platform or Programs if you are not happy with any changes to these Terms.</p>
         <p className="terms-of-use-para">bitLabs makes no representations that the Platform operates (or is legally permitted to operate) in all geographic areas, or that the Platform, or information, services or products offered through the Platform are appropriate or available for use in other locations. Accessing the Platform from territories where the Platform, or any content or functionality of the Platform or its portions thereof is illegal, is expressly prohibited. If you choose to access the Platform, you agree and acknowledge that you do so on your own initiative and at your own risk and that you are solely responsible for compliance with all applicable laws.</p>
         <p className="terms-of-use-subheading">User Conduct Policy</p>
         <p className="terms-of-use-para">Whether you have enrolled in a Program or are simply browsing the Platform, once you have accessed the Platform or Programs, you shall be considered a ‘user’ for the purpose of these Terms. You are responsible for all your activities in connection with the use of the Platform and Programs. You hereby agree to fully comply with all applicable local, provincial, state, national and foreign laws, treaties and regulations in connection with such use. You shall not resort to any unethical practices while using the Platform.</p>
         <p className="terms-of-use-para">Without limitation, you will not post or transmit, or cause to be posted or transmitted, any communication or solicitation or other "phishing", "pharming" or "whaling" message designed or intended to obtain password, account, personal information, confidential information or private information from any user of the Platform or any other third party whatsoever. However, if any such event does take place, bitLabs shall not be liable for any loss of data or if the user’s device, computer or any other property is compromised in any manner.</p>
         <p className="terms-of-use-para">You acknowledge and agree that bitLabs has the right to report any and all suspicious or illegal activity to the appropriate legal or police authorities without notice to you.</p>
         <p className="terms-of-use-para">During your use of the Platform and Programs, you will:</p>
         <div className="ul-bullets">
         <ul className="terms-of-use-para">
             <li>Not harass other users, students, attendees, support advisors, instructors, mentors or visitors;</li>
             <li>Not create an atmosphere of disharmony, hostility within student groups;</li>
             <li>Not cheat on any homework assignment or exams for the Program;</li>
             <li>Not post online any secured testing materials;</li>
             <li>Not share solutions to homework assignments or exams; and notify the instructors immediately if you become aware of any other user cheating or breaching these Terms, and comply with the requirements of the specific applicable code of conduct, if any, relating directly to a Program into which such user is enrolled.</li>
         </ul>
         </div>
         <p className="terms-of-use-subheading">User Accounts, User Registration and Delivery of Services</p>
         <p className="terms-of-use-para">In order to participate in most Platform activities and to apply for a Program, you will need to register for a personal account (“User Account”) by providing an email address and a password that is unique.</p>
         <p className="terms-of-use-para">Upon payment of the Program fees – in part or whole, depending on the Program – bitLabs shall deliver the terms of use of the Program and grant you access to the Program. The invoice may be provided to you along with the email confirmation or within one (1) months thereafter. This shall be proof of delivery against the successful payment of fees.</p>
         <p className="terms-of-use-para">Owing to certain exceptional circumstances, if bitLabs has granted you access to a Program pending payment, and bitLabs does not receive payments within the stipulated time periods, bitLabs may, at its own discretion, withdraw your access to the Program without giving any prior notice.</p>
         <p className="terms-of-use-para">You agree that you will never divulge or share access to your User Account with any third party for any reason. You also agree that you will create, use and/or access only one User Account, and that you will not use any User Account other than your own.</p>
         <p className="terms-of-use-para">In setting up your User Account, you may be prompted or required to enter additional information, including but not limited to your name and email address. Additional information may be required to confirm your identity. You understand and agree that all information provided by you is accurate, current and complete and that you will maintain and update your information to keep it accurate, current and complete. You acknowledge that if any information provided by you is untrue, inaccurate, not current or incomplete, we reserve the right to terminate your use of the Platform and your enrolment into a Program, to the extent applicable.</p>
         <p className="terms-of-use-para">In addition to the registration process, as part of your use of the Platform or participation in the Programs, we may obtain certain information about you and your performance in the Programs. Some of this information may be Personally Identifiable Information. We may use, maintain and store this information to provide certain services to you now and in the future, and may share such information with our Educational Partners or third parties in conjunction with such services or for the purpose of marketing and recruiting. For example, as further detailed in our Privacy Policy, we may share certain materials or information about you with third parties, including your grades/scores in our classes.</p>
         <p className="terms-of-use-para">Access to the Programs is restricted to attendees or students who have specifically been granted access by bitLabs.</p>
         <p className="terms-of-use-para"> By registering your User Account, you agree that:</p>
         <div className="ul-bullets">
         <ul className="terms-of-use-para">
             <li>You are registered for the Program only once and will not set up multiple User Accounts; and</li>
             <li>You will abide by these Terms and any terms specific to the Program.</li>
         </ul>
         </div>
         <p className="terms-of-use-subheading">Payment Terms and Refund Policy</p>
         <p className="terms-of-use-para">Unless otherwise expressly agreed in writing by bitLabs, full payment for participation in a Program is required at the time of registration. In the case of Programs that include a trial window, such trial window shall be made available only after the full payment. During the trial window, upon a request by the Student, and to the satisfaction of bitLabs, bitLabs may choose to refund the Program Fees paid, subject to such charges as may be decided from time to time. Once the trial window has closed, there will be no refund allowed for any reason whatsoever.</p>
         <p className="terms-of-use-para">It is the sole responsibility of the user enrolling into a Program to check the accuracy of, and evaluate the suitability and relevance of, the Program elected. The enrolment into a Program is non-transferable.</p>
         <p className="terms-of-use-para">To make payment for any Program or to purchase any services or products offered by bitLabs through the Platform, you must have internet access and a current valid accepted payment method as indicated during sign-up ("Payment Method"). bitLabs does not store any of your credit card information or such other information restricted by the Reserve Bank of India (RBI) for processing payment and has partnered with payment gateways for the payment towards the services. By using a third-party payment provider, you agree to abide by the terms of such a payment provider. You agree that in case bitLabs’s third-party payment provider stores any such information, bitLabs will not be responsible for such storage, and it will be solely at your discretion to allow the third party to store such information. Any loss of such information or any loss incurred by you due to the usage of such information will be solely a loss incurred by you, and bitLabs is in no way liable for any such losses and is neither responsible to reimburse / make good such losses in any manner whatsoever. You also agree to pay the applicable fees for the payments made through the Platform.</p>
         <p className="terms-of-use-para">Failure to pay may result in withdrawal of your access to a Program. Depending on where you transact with us, the type of payment method used and where your payment was issued, your transaction with us may be subject to foreign exchange fees or exchange rates. bitLabs does not support all payment methods, currencies or locations for payment. All applicable taxes are calculated based on the billing information you provide to us at the time of enrolment/purchase.</p>
         <p className="terms-of-use-para">You may cancel your enrolment at any time. No refund will be made once the payment (in part or whole) for a Program has been made. We do not provide refunds for the lack of usage or dissatisfaction.</p>
         <p className="terms-of-use-para">If you have subscribed for a free trial, the free trial period will last for the period of time specified during your sign-up. Free trials may not be combined with certain other offers. If you have subscribed to a particular paid service or product within the last six (6) months, or if your Payment Method, physical address or email address has been associated with an account for that paid service, you are not eligible to receive a free trial for that service or product. If you begin your subscription with a free trial, you may be ineligible for certain features of a product or service during your free trial period.</p>
         <p className="terms-of-use-subheading"> Use of Programs</p>
         <p className="terms-of-use-para"> bitLabs reserves the right to cancel or reschedule any Program or live lectures/webinars, or to alter, modify or rearrange the schedule of topics, as well as the point value or weight of assignments, tests, quizzes, exams, projects and other such evaluations of progress. You also understand that bitLabs, at its sole discretion, may limit, suspend, or terminate your use of the Platform or Programs and/or all bitLabs-provided services related to the Programs, such as access to bitLabs coaches or support services, evaluation services, or certifications. You also understand that bitLabs may modify or discontinue all services related to its Programs at its sole discretion. You agree that bitLabs shall not be liable to you or to any third party for any such modification, suspension or discontinuance. Nothing in these Terms shall be construed to obligate bitLabs to maintain and support the Platform or Programs or any part or portion thereof or any associated services.</p>
         <p className="terms-of-use-para">If you no longer wish to use any Program, you may terminate your participation by giving notice to bitLabs.</p>
         <p className="terms-of-use-para">Participants of bitLabs online live lectures and webinars, if applicable, shall be provided access to such classes via email. You agree not to share such access with any third party. If you are unable to attend an online live lecture/webinar, please provide bitLabs with prior intimation regarding this.</p>
         <p className="terms-of-use-para">You shall be exclusively responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access, receive or use the Platform, including, without limitation, hardware devices, software, and other internet, wireless, broadband, phone or other mobile communication device connection services. You shall be exclusively responsible for ensuring that such equipment or ancillary services are compatible with the Platform, and you shall be responsible for all charges incurred in connection with the use of the Platform and Program in connection with all such equipment and ancillary services.</p>
         <p className="terms-of-use-subheading">Educational Partners and Accreditation</p>
         <p className="terms-of-use-para">bitLabs is NOT a University, but an education service provider, offering Programs in consultation with industry organizations, corporates, etc. (each an “Educational Partner”).</p>
         <p className="terms-of-use-para">Admission to the degree/diploma programs of an Educational Partner is separate from being accepted into and/or taking one or more Programs. You agree and acknowledge that nothing in these Terms or otherwise with respect to the use of the Platform or any Program (a) enrolls or registers you in an Educational Partner, or any other school, division, institute or program of or associated with an Educational Partner, and (b) allows you to access or use the resources or receive any benefits or privileges of any Educational Partner, beyond the Programs.</p>
         <p className="terms-of-use-para">bitLabs may offer a credential or other acknowledgement for participants who have satisfactorily demonstrated mastery of the Program material. The decision to award any such credential acknowledgement to a given participant will be solely at the discretion of bitLabs. bitLabs may choose not to offer any credential or other acknowledgement for some Programs. bitLabs may decide at its sole discretion whether to provide a record concerning a participant’s performance in a Program. The format of any credential or other acknowledgement, and of any performance, provided by bitLabs relating to Programs will be determined by bitLabs at its sole discretion and may vary from Program to Program.</p>
         <p className="terms-of-use-para">You will be awarded a certificate of successful completion of a Program (“Program Certificate”) upon fulfilling the criteria and requirements of bitLabs and its Educational Partners. You acknowledge that any such Program Certificate awarded may not be affiliated to any Educational Partner and may not stand in the place of a course taken with an Educational Partner or convey academic credit or certification for any Educational Partner.</p>
         <p className="terms-of-use-para">You will not receive academic credit from bitLabs or any other Educational Partner for taking a Program. If you are taking a Program for academic credit or certification as a student of, or otherwise through, an Educational Partner, any such credit or certification may only be awarded directly by the Educational Partner based on its own policies and procedures, and you may be required by that Educational Partner to be registered or enrolled with the Educational Partner in order to receive credit or certification; and, in any event, bitLabs will not have any authority or responsibility with respect to any award of academic credit or certification provided by an Educational Partner for a Program.</p>
         <p className="terms-of-use-para">You acknowledge and agree that any Program affiliated with an Educational Partner may be subject to the terms, policies and procedures of the applicable Educational Partner in addition to bitLabs’s Terms. Without limiting the foregoing, if you are a student registered or enrolled at, or are otherwise attending, an Educational Partner and are taking a Program for credit or certification through that Educational Partner, you acknowledge and agree that (a) the Educational Partner may have its own terms, policies or procedures regarding your eligibility to participate in the Program, your participation in the Program, the requirements or prerequisites for receiving credit or certification for the Program, and/or your educational or student records as they may relate to your participation and performance in the Program, and (b) your educational or student records are maintained by the Educational Partner, including for purposes of assigning credit or certification, and not bitLabs.</p>
         <p className="terms-of-use-subheading">bitLabs’s Intellectual Property Rights</p>
         <p className="terms-of-use-para">“Content” means any and all information and data, which may include but not be limited to text, software, scripts, graphics, maps, photos, sounds, music, videos, logos, offers, advertisements, interactive features and other materials.</p>
         <p className="terms-of-use-para">The Platform, Programs and related services are owned and operated by bitLabs and its licensors. All Content or other material available on the Platform or through the Programs, including but not limited to online/live lectures, speeches, video lessons, quizzes, presentation materials, homework assignments, programming assignments, programs, code, and other images, text, layouts, arrangements, displays, illustrations, documents, materials, audio and video clips, HTML and files (collectively “bitLabs Content”), are the property of bitLabs and/or its affiliates or licensors, and are protected by copyright, patent and/or other proprietary intellectual property rights under Indian and foreign laws. All software used on the Platform is the property of bitLabs and is protected by Indian and international copyright laws.</p>
         <p className="terms-of-use-para">bitLabs logos, trademarks and service marks that may appear on the Platform and in the Program (“bitLabs Marks”) are the property of bitLabs and are protected under Indian and foreign laws. All other trademarks, service marks and logos used on the Platforms, Online Courses or Programs, with or without attribution, are the trademarks, service marks or logos of their respective owners. In addition, elements of the Platforms are protected by trade dress and other Indian and international intellectual property laws and may not be copied, reproduced, downloaded or distributed in any way in whole or in part without the express written consent of bitLabs.</p>
         <p className="terms-of-use-para">As a condition of accessing the Platforms and/or using the Programs, you agree not to (a) reproduce, duplicate, copy, sell, resell or exploit for any commercial purpose any bitLabs Content or any portion of it thereof, other than as expressly allowed under these Terms; and (b) use the bitLabs Marks or the name, trademarks, service marks, or other materials of any Educational Partner in connection with, or to transmit, any unsolicited communications or emails or for any other unauthorised purpose.</p>
         <p className="terms-of-use-para">Please verify all Content prior to use. In the event you come across any Content that is incorrect, infringing, offensive, indecent or objectionable, please notify us immediately at the address mentioned at the bottom of this page.</p>
         <p className="terms-of-use-para">Additionally, from time to time, bitLabs (or its third-party service providers, on behalf of bitLabs) may request users to review bitLabs Content or beta-test the Platform. The works derived from such activity shall remain the sole and exclusive property of bitLabs or its third-party service providers, as applicable.</p>
         <p className="terms-of-use-subheading">Third-Party Intellectual Property</p>
         <p className="terms-of-use-para">bitLabs respects third-party intellectual property rights and actively supports protection of all third-party intellectual property including copyrights and trademarks (“IP”). It is our policy to expeditiously respond to clear notices of alleged IP infringement. If we receive proper notification of IP infringement, our response to such notices will include removing or disabling access to material claimed to be the subject of infringing activity.</p>
         <p className="terms-of-use-para">bitLabs shall not be held liable for the unauthorised use of any third-party IP, and the user that carries out such unauthorised use or infringes any IP available on the Platform shall fully indemnify and hold bitLabs harmless against any and all claims that may arise as a result of such use.</p>
         <p className="terms-of-use-para">If you believe that your product or other work has been misrepresented or used in a way that constitutes copyright infringement, or your intellectual property rights have been otherwise violated, please provide us with the following information:</p>
         <div className="ul-bullets">
         <ul className="terms-of-use-para">
             <li>An electronic or physical signature of the person authorised to act on behalf of the owner of the product, copyright or other intellectual property interest;   </li>
             <li>A description of the product, work or other intellectual property that you claim has been misrepresented or infringed;  </li>
             <li>A description of where the material that you claim is misrepresenting or infringing your product, work or other intellectual property is located on the Platform/Program;  </li>
             <li>Your address, telephone number, and email address;   </li>
             <li>A statement by you that you have a good faith belief that the disputed use is not authorised by the owner of the product, work, copyright or intellectual property, or its agent, or applicable law; and  </li>
            <li>A statement by you, made under the penalty of perjury, that the aforementioned information in your notice is accurate and that you are the product, work, copyright or intellectual property owner or authorised to act on such owner's behalf.  </li>
        </ul>
        </div>
        <p className="terms-of-use-para">For notices of disputes or claims of copyright or other intellectual property infringement, please connect with us at the address provided at the bottom of this page.</p>
        <p className="terms-of-use-subheading"> Limited License</p>
        <p className="terms-of-use-para">The services on the Platform are licensed, not sold. In consideration for your agreement to these Terms, bitLabs grants you a personal, non-exclusive, non-transferable, revocable license to access and use the Platform and Programs, solely in accordance with the Terms. You may download or copy the portions of the bitLabs Content available on the Platform for your own non-commercial and personal use only, provided you maintain all copyright and other notices contained in such bitLabs Content. You may not copy, sell, resell, reproduce, publish, modify, transfer, retransmit, distribute, commercially exploit or create derivative works of Platforms, Programs or any bitLabs Content. You may not reverse-engineer, decompile, disassemble or otherwise code for any software that may be used to operate the Platform or the Programs. Notwithstanding the foregoing, certain reference documents, digital textbooks and articles may be made available to you with the permission of third parties, and use of that information is subject to certain rules and conditions, and you agree to abide by all such rules and conditions.</p>
        <p className="terms-of-use-para">You may not reverse-engineer, decompile, disassemble or otherwise access the source code for any software that may be used to operate the Platform or the Programs. From time to time, bitLabs may include software, code, instructions, or other such information in the bitLabs Content for the Programs; any such information is provided on an "as-is" basis for instructional purposes only and is subject to the ‘Disclaimer’ and ‘Limitation of Liability’ sections below and other terms herein. Any use of such information for commercial purposes is strictly prohibited. bitLabs and/or its affiliates and licensors reserve all rights not expressly granted herein to the Platforms, bitLabs Content, and bitLabs Marks.</p>
        <p className="terms-of-use-para">Without limiting the generality of the terms above, the following are types of uses that bitLabs expressly defines as falling outside of the definition of "non-commercial and personal use":</p>
        <div className="ul-bullets">
       <ul className="terms-of-use-para">
        <li>The sale or rental of (i) any part of the bitLabs Content, (ii) any derivative works based at least in part on the bitLabs Content, or (iii) any collective work that includes any part of the bitLabs Content;</li>
        <li>The sale of access or a link to any part of the bitLabs Content;</li>
        <li>Providing training, support, or editorial services that use or reference the bitLabs Content in exchange for a fee;</li>
        <li>The use of bitLabs Content by a college, university, school, or other educational institution for instruction where tuition is charged;</li>
        <li>The use of bitLabs Content by a for-profit corporation or non-profit entity for internal professional development or training; and</li>
        <li>The use of bitLabs Content for display / upload / making available at a place that is accessible to the general public in any manner, including but not limited to any social media sites, video download sites, and torrents.</li>
       </ul>
       </div>
       <p className="terms-of-use-subheading">User Content</p>
       <p className="terms-of-use-para">The Platform may allow you to upload forum posts, chat with other users and bitLabs’s counsellors, user discussions, profile pages, and other content and media for social interaction, or certain information and materials for use with the Programs, e.g., questions, hypotheticals, examples, assignments, industry projects, etc. (collectively "User Content"). bitLabs does not claim ownership of any User Content you may submit or make available for inclusion on the Platform or Programs. Accordingly, subject to the license granted to bitLabs above, the user will be the sole and exclusive owner of any and all rights, title and interest in and to the User Content.</p>
       <p className="terms-of-use-para">With respect to any User Content you submit via the Platform or Programs or that is otherwise made available to bitLabs, you hereby grant bitLabs an irrevocable, worldwide, perpetual, royalty-free and non-exclusive license to use, distribute, reproduce, modify, adapt, publicly perform and publicly display such User Content on the Platforms or in the Programs or otherwise exploit the User Content, with the right to sublicense such rights (to multiple tiers), for any purpose (including for any commercial purpose). bitLabs reserves the right to remove any User Content at any time and for any reason.</p>
       <p className="terms-of-use-para">To the extent that you provide any User Content, you represent and warrant that (a) you have all necessary rights, licenses and/or clearances to provide such User Content and permit bitLabs to use such User Content as provided above, (b) such User Content is accurate and reasonably complete, (c) as between you and bitLabs, you shall be responsible for the payment of any third-party fees related to the provision and use of such User Content, and (d) such User Content does not and will not infringe or misappropriate any third-party rights or constitute a fraudulent statement or misrepresentation or unfair business practices.</p>
       <p className="terms-of-use-para">bitLabs does not control the User Content posted through the Platform, including any messages, reviews or comments, and does not guarantee the accuracy, integrity or quality of such User Content. Under no circumstances will bitLabs be liable in any way for any User Content, including any errors or omissions, or any loss or damage or defamation of any kind incurred as a result of your posting or use of any User Content. You are responsible for complying with all the laws applicable to the User Content.</p>
       <p className="terms-of-use-para">You are prohibited from posting the following Content on the Platform:</p>
       <div className="ul-bullets">
       <ul className="terms-of-use-para">
           <li>Content that is fraudulent, indecent, or libellous, or defames, harasses, discriminates against, harms or threatens others;</li>
           <li>Content that discusses illegal activities, with the intent to commit them;</li>
           <li>Content that infringes or misappropriates patents, trademarks, trade secrets, right of publicity, or other intellectual property rights of third parties;</li>
           <li>Content that you do not have the right to disclose;</li>
           <li>Profane, pornographic, obscene, indecent or unlawful Content;</li>
           <li>Advertising or any form of commercial solicitation;</li>
           <li>Content related to partisan political activities;</li>
           <li>Content that contains intentionally inaccurate information or that is posted with the intent of misleading others;</li>
           <li>Viruses, Trojan horses, worms, time bombs, cancelbots, or other disabling devices or other harmful components intended to or that may damage, detrimentally interfere with, surreptitiously intercept, or expropriate any system, data, or personal information;</li>
           <li>Content that consists of any high volume, automated, or electronic means to access the Platform (including without limitation robots, spiders or scripts);</li>
           <li>Content that violates the rights of other users of the Platform; or</li>
           <li>Content that violates any applicable local, state, national or international law or otherwise advocates or encourages any illegal activity.</li>
       </ul>
       </div>
       <p className="terms-of-use-subheading">Platform Security</p>
       <p className="terms-of-use-para">You are prohibited from violating or attempting to violate the security of the Platform or any other associate Platform of bitLabs, including, without limitation, (a) accessing data not intended for such user or logging onto a server or an account that the user is not authorised to access; (b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorisation; (c) attempting to interfere with service to any user, host or network, including, without limitation, via means of submitting a virus to the Platform, overloading, "flooding," "spamming," "mailbombing" or "crashing;" (d) sending unsolicited emails, including promotions and/or advertising of products or services; or (e) forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting. Violations of system or network security may result in civil or criminal liability. bitLabs will investigate occurrences that may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of this Platform or any activity being conducted on the Platform. You agree, further, not to use or attempt to use any engine, software, tool, agent or other device or mechanism (including without limitation browsers, spiders, robots, avatars or intelligent agents) to navigate or search the Platform other than the search engine and search agents available from bitLabs on the Platform and other than generally available third-party web browsers (e.g., Google Chrome or Microsoft Explorer).</p>
       <p className="terms-of-use-subheading">Disclaimer</p>
       <p className="terms-of-use-para">The Platform and/or Programs may contain typographical errors or inaccuracies and may not be complete or current. bitLabs, therefore, reserves the right to correct any errors, inaccuracies or omissions (including after an order has been submitted) and to change or update information at any time without prior notice.</p>
       <p className="terms-of-use-para">The Platform, Programs, and any information or bitLabs Content are provided on an “as is” and “as available” basis with all faults.</p>
       <p className="terms-of-use-para">bitLabs makes no representations or warranties of any kind, whether expressed or implied, with respect to bitLabs Content or services available on or through this Platform and Programs, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. bitLabs makes no warranty that the services will meet the user's requirements or that the services will be uninterrupted, timely, secure, or error free; nor does bitLabs make any warranty as to the results that may be obtained from the use of the services, or as to the accuracy or reliability of any information obtained through the services, or that any defects in the software will be corrected.</p>
       <p className="terms-of-use-para">The user understands and agrees that the bitLabs Content and all other information, data, or other material downloaded or otherwise obtained through or from the Platform or Programs is obtained at the user's own discretion and risk, and that the user will be solely responsible for any damage to the user, the user's computer system, electronic device or any loss of data that results from the download of such material or data.</p>
       <p className="terms-of-use-para">No advice or information, whether oral or written, obtained by the user from bitLabs or through or from the services, shall create any warranty by bitLabs.</p>
       <p className="terms-of-use-para">In the event you find that the information provided on the Platform or Programs is incorrect, or if you are the owner of any information or content and wish that such information or content is not displayed on the Platform or Programs, kindly notify us at the address provided at the bottom of the page.</p>
       <p className="terms-of-use-subheading">Limitation of Liability</p>
       <p className="terms-of-use-para">Neither bitLabs nor any of its Educational Partners, affiliates, employees, directors, officers, agents, vendors or supplier shall be liable to you or any other person, whether in Tort, Contract, Strict Liability or otherwise, for any indirect, special, incidental or consequential losses or damages of any nature arising out of or in connection with the use or inability to use this Platform or Programs, including, without limitation, damages for lost profits, loss of goodwill, loss of data, work stoppage, accuracy of search results, or computer / electronic device failure, virus or malfunction. In no event will bitLabs be liable for any damages in excess of ₹500 or, in the case of enrolled students, the fees paid by you in connection with your enrolment into a Program.</p>
       <p className="terms-of-use-subheading">Site Linking</p>
       <p className="terms-of-use-para">The Platform may contain links to pages on other websites ("Linked Sites"), and those Linked Sites may contain Content or offer products and/or services for sale. bitLabs does not author, edit, control, or monitor these Linked Sites. You acknowledge and agree that (a) we have no responsibility for the accuracy or availability of information provided by Linked Sites; (b) we do not control or endorse the sponsors of such Linked Sites or the content, products, advertising, or other materials presented on such Linked Sites; and (c) you agree to the terms and conditions of the Linked Sites. We may remove any Linked Sites from the Platform at any time with or without reason.</p>
       <p className="terms-of-use-para">bitLabs WILL NOT BE LIABLE FOR ANY TRANSACTIONS CONDUCTED BY YOU WITH THIRD PARTIES THROUGH THE LINKED SITES OR FOR ANY LIABILITY ARISING FROM THE REPRESENTATIONS OR INFORMATION PROVIDED ON SUCH LINKED SITES.</p>
       <p className="terms-of-use-para">We appreciate that Linked Sites may contain material on which the operator of the Linked Sites has intellectual property rights. We respect those rights and provide the links for information purposes only. The fact that we have provided links to any Linked Site does not create or imply any relationship or partnership with the operator of such Linked Site.</p>
       <p className="terms-of-use-para">You may not establish a link to this Platform from any other website, application, intranet or extranet site without our prior written consent. If you wish to create links, you may contact us before doing so. In establishing links, you must not represent in any way, expressly or by implication, that you have received the endorsement, sponsorship or support of bitLabs, including its Educational Partners, respective employees, agents, directors, officers or shareholders.</p>
       <p className="terms-of-use-subheading">Indemnity</p>
       <p className="terms-of-use-para">You agree to indemnify and hold bitLabs and its Educational Partners harmless from any and all claims, liabilities, damages, losses and expenses, including reasonable attorneys' fees and costs, relating to or arising out of (a) your use or attempted use of the Platforms or Programs in violation of the Terms; (b) your violation of any law or rights of any third party; or (c) information or Content that you or others post or otherwise make available on the Platform or through any Program, including without limitation any claim of infringement or misappropriation of intellectual property or other proprietary rights.</p>
       <p className="terms-of-use-subheading"> Termination of Rights</p>
       <p className="terms-of-use-para">You agree that bitLabs, in its sole discretion, may deactivate your account or otherwise terminate your use of the Platform or enrolment to a Program with or without reason, including, without limitation, if bitLabs believes that you have (a) breached the Terms; (b) infringed the intellectual property rights of a third party; (c) posted, uploaded or transmitted unauthorised Content on the Platform; or (d) violated or acted inconsistently with the letter or spirit of these Terms or any other applicable code of conduct. You agree that any deactivation or termination of your access to the Platforms or Programs may be effected without prior notice to you and that bitLabs shall not be liable to you nor any third party for any termination of your account or enrolment into a Program. You also acknowledge that bitLabs may retain and store your information on bitLabs’s systems notwithstanding any termination of your account or enrolment into the Programs.</p>
       <p className="terms-of-use-subheading">Miscellaneous Provisions</p>
       <p className="terms-of-use-para">By accepting the Terms through your use of the Platform, you certify that you are 18 years of age or older. If you are under the age of 18 or under the legal age in your jurisdiction to enter into a binding contract, you may use the Platform only under the supervision of a parent or legal guardian who agrees to be bound by the Terms. If you are a parent or legal guardian agreeing to the Terms for the benefit of a child below 18, be advised that you are fully responsible for his/her use of the Platform, including all financial charges and legal liability that he/she may incur. By using the Platform, you represent and warrant that you have the right, authority, and capacity to enter into the Terms and to abide by all of the terms and conditions set forth herein. The Programs are not for the use of individuals under the age of 18 years.</p>
       <p className="terms-of-use-para">bitLabs may freely transfer or assign any portion of its rights or delegate its obligations under these Terms or any Program specific terms. You shall not transfer or assign, by operation of law or otherwise, any portion of your rights or delegate your obligations under these Terms or any Program-specific terms without the prior written consent of bitLabs.</p>
       <p className="terms-of-use-para">These Terms or any Program-specific terms shared with you shall be governed by, construed and enforced in accordance with the laws in India, as these are applied to agreements entered into and to be performed entirely within India and without giving effect to any principles of conflict of laws. You agree that any legal lawsuit or other action brought by bitLabs, you or any third party to enforce these Terms or any Program-specific terms shared with you, or in connection with any matters related to the Platform or Programs, shall be subject only to the jurisdiction of the courts of Vijayawada. Where a dispute arises, the parties involved shall make all reasonable efforts to resolve the dispute through good faith negotiations. If efforts to amicably resolve any dispute or claim between the parties are unsuccessful, then such dispute or claim arising out of or in connection with the Terms or any Program-specific terms shared with you, including any question regarding its existence, validity or termination, shall be referred to arbitration under the Arbitration and Conciliation Act, 1956, as amended (“Act”) before a sole arbitrator to be appointed by bitLabs. The proceedings shall be conducted in English and the seat for arbitration shall be Vijayawada.</p>
       <p className="terms-of-use-para">If any provision of the Terms or any Program-specific terms shared with you is found to be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from the other provisions herein, and shall not affect the validity and enforceability of any remaining provisions. bitLabs shall have no liability under these Terms or any Program-specific terms shared with you, to the extent arising from any failure of bitLabs to perform any of its obligations under these Terms or any Program-specific terms shared with you, due to any fire, flood, earthquakes, other acts of God, war, civil unrest, terrorism, Internet failures, governmental act or court order, national emergency, strikes or labour disputes or any other event not within bitLabs 's reasonable control. bitLabs shall not be responsible for damage or other problems caused by any unauthorised change to these Terms made by way of hacking or cracking this page.</p>
       <p className="terms-of-use-para">The failure of bitLabs to exercise or enforce any right or provision of the Terms or any Program-specific terms shared with you, shall not constitute a waiver of such right or provision. If any provision of the Terms or any Program-specific terms shared with you is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavour to give effect to the parties' intentions as reflected in the provision, to the extent that may lawfully be done, and the other provisions of these Terms or any Program-specific terms shared with you, shall remain in full force and effect.</p>
       <p className="terms-of-use-para">These Terms or any Program-specific terms shared with you constitute the entire agreement between you and bitLabs relating to the matters set forth herein, and shall not be modified except in writing, as posted on the Platforms by bitLabs or through a specific writing between you and bitLabs.</p>
       <p className="terms-of-use-para">bitLabs may freely transfer or assign any portion of its rights or delegate its obligations under the Terms or any Program-specific terms shared with you. You may not transfer or assign, by operation of law or otherwise, any portion of your rights or delegate your obligations under the Terms or any Program-specific terms shared with you, without the prior written consent of bitLabs, and any such attempted transfer or assignment shall be void and of no effect.</p>
       <p className="terms-of-use-para">Any notice or communication that may be required to be given to bitLabs under these Terms or any Program-specific terms shared with you may be sent by writing or emailing to the following addresses: legal@bitlabs.in</p>
       </div>
       </div>
        </div>
    )}